### ISSUE TITLE
CVP problem continue

### ISSUE THREAD

**Issue by ZiqiangMa** [fplll/fpylll#132]
The same problem in the [last question](https://github.com/fplll/fpylll/issues/131#issue-417695318)

I don't think it is the closest vector. I refer to the tutorial of fpylll, and use `Enumeration `to implement the CVP. the code is:

```
M = GSO.Mat(copy(CVPlattice), float_type='dd')
M.update_gso()
E = Enumeration(M)
_, v1 = E.enumerate(0, A2.nrows, 2, 40, M.from_canonical(u_target))[0]
v1 = IntegerMatrix.from_iterable(1, A2.nrows, map(lambda x: int(round(x)), v1))
v1 = tuple((v1*A2)[0])
```
and the result is:

_End of BKZ: success
Traceback (most recent call last):

File "", line 1, in 
runfile('/home/mzq/.config/spyder-py3/attack_ecdsa.py', wdir='/home/mzq/.config/spyder-py3')

File "/home/mzq/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 704, in runfile
execfile(filename, namespace)

File "/home/mzq/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
exec(compile(f.read(), filename, 'exec'), namespace)

File "/home/mzq/.config/spyder-py3/attack_ecdsa.py", line 258, in 
_, v1 = E.enumerate(0, A2.nrows, 2, 40, M.from_canonical(u_target))[0]

File "src/fpylll/fplll/enumeration.pyx", line 385, in fpylll.fplll.enumeration.Enumeration.enumerate

EnumerationError: No solution found._

So what should be done to this case. Thank you very much.

**Comment by malb** [comment]
Maybe there is no solution within distance `2^40`? Hard to tell from your report.
