### ISSUE TITLE
Python 3.12

### ISSUE THREAD

**Issue by malb** [fplll/fpylll#256]
No more `setuptools` or `distutils` apparently, and we need to rewrite our `setup.py` :(

```
Traceback (most recent call last):
  File "/home/runner/work/fpylll/fpylll/setup.py", line 25, in <module>
    from setuptools.command.build_ext import build_ext as _build_ext
ModuleNotFoundError: No module named 'setuptools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fpylll/fpylll/setup.py", line 30, in <module>
    from distutils.command.build_ext import build_ext as _build_ext
ModuleNotFoundError: No module named 'distutils'
```

https://github.com/fplll/fpylll/actions/runs/6530587177/job/17730158655

**Comment by malb** [comment]
Any volunteers?
